sudo: required

language: node_js

node_js:
  - "10.15.1"

before_install: # if "install" is overridden
  # Repo for Yarn
  #- sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  #- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  #- sudo apt-get update -qq
  #- sudo apt-get install -y -qq yarn=1.17.3-1
  - npm install -g yarn@1.17.3

install:
  - yarn

cache:
  yarn: true
  directories:
    - "node_modules"


deploy:
  provider: elasticbeanstalk
  access_key_id: $EB_ACCESS_KEY_ID
  secret_access_key: $EB_SECRET_KEY
  region: "us-east-1"
  app: "ewwb"
  env: "production"
  bucket_name: "elasticbeanstalk-us-east-1-837534802860"