# Miscellaneous Elastic Beanstalk settings
option_settings:
  aws:elasticbeanstalk:application:environment:
    NODE_ENV: production
    NPM_CONFIG_PRODUCTION: true

  aws:elasticbeanstalk:container:nodejs:
    NodeCommand: "yarn start"
    ProxyServer: nginx
    GzipCompression: true

  aws:elasticbeanstalk:container:nodejs:staticfiles:
    option_name: /static/
    value: /public/